# Generated by Django 2.2.12 on 2020-05-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=10)),
                ('part_supplier', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('part_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.IntegerField(default=0)),
                ('po_qty', models.IntegerField(default=1)),
                ('pn_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logisapp.Part')),
            ],
        ),
    ]
