# Generated by Django 2.2.12 on 2020-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='po_number',
            field=models.CharField(max_length=5),
        ),
    ]
