# Generated by Django 2.2.12 on 2020-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisapp', '0002_auto_20200510_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PO',
        ),
    ]
